max_epochs: 1
batch_size: 2
num_workers: 4
precision: 32
optimizer:
  lr: 1e-3
model:
  fmri_input_dim: 2048 # placeholder ROI vectorizat
  latent_dim: 768 # țintă CLIP text/image latent (placeholder)
  hidden: [2048, 1024, 768]
loss:
  type: "contrastive" # "contrastive" | "cosine"
  temperature_init: 0.07 # initial temperature for InfoNCE (CLIP-style)
  symmetric: true # use both fMRI->text and text->fMRI
eval:
  topk: [1, 5]
