max_epochs: 1
batch_size: 2
num_workers: 4
precision: 32
optimizer:
  lr: 1e-3
model:
  fmri_input_dim: 2048 # placeholder ROI vectorizat
  latent_dim: 768 # țintă CLIP text/image latent (placeholder)
  hidden: [2048, 1024, 768]
